--create tables

--user table for user reg info
CREATE TABLE USER (
    ID INT(12) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    REG_DATE TIMESTAMP
)